#!/bin/bash
if [ -f ~/.tmplrc ]; then
  . ~/tmplrc
fi

projectTemplateDir="${PROJECT_TEMPLATE_DIR}"

printUsage() {
  echo "Usage"
  echo "  ls | list:                   List Project Templates"
  echo "  init <template> <dest>:      Initialize a template into a new directory"
}

init () {
  src="$1"
  dest="$2"

  if [ "$src" = "" ] | [ "$dest" = "" ]; then
    echo "Missing source or destination"
    echo ""
    printUsage
    exit 1
  fi

  if [ ! -d "$projectTemplateDir/$src" ]; then
    echo "Project template $projectTemplateDir/$src does not exist"
    exit 2 
  fi
  
  cp -r "$projectTemplateDir/$src" "$dest"
  rm -f "$dest/.git"
  (cd $dest && git init)
}

if [ "$projectTemplateDir" = "" ]; then
  echo "You need to set the project template directory. You can either do this by setting PROJECT_TEMPLATE_DIR or creating a .tmplrc file in your home dir"
fi

arg=$1

if [ "$arg" = "" ]; then
  printUsage
fi

case "$arg" in
  ls|list)
    ls $projectTemplateDir
  ;;
  init)
    init $2 $3
  ;;
  *)
    printUsage
  ;;
esac
